name: Perennialle Plants
favicon: null
layout_spectrum: 1
typography_spectrum: 0.14518
title: Frost and dry tolerant plants and perenials
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7aa89'
    - '#313f40'
    - '#122023'
    - '#807571'
    - '#c9cbb7'
  brandStrength: 0.75
  lightness: 0.4990336033515632
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
